config/routes.rb
Rails.application.routes.draw do
  
  root 'page#index'
  
  post 'access/attempt_login'
  get 'access/logout'
  
  resources :users do
    member do
      get :delete
    end
  end
  post 'users/addmoney'
  post 'users/retiremoney'
  
  resources :transfers do
    member do
      get :delete
    end
  end
  
  resources :commissions do
    member do
      get :delete
    end
  end
  
  get 'page/index'

  get 'page/profile'

  get 'page/register'

  get 'page/login'
  
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/page/index.html.erb
<% @linkactive = 'index' %>
<% if @user.id? %>
<h1 class="cover-heading">Bienvenido de vuelta <strong><%= @user.name %></strong></h1>
<p class="lead">Entra a tu perfil para realizar tus operaciones.</p>
<p class="lead">
  <a href="/page/profile" class="btn btn-lg btn-primary">Ir al Perfil</a>
</p>
<% else %>
<h1 class="cover-heading">EWallet Conekta.</h1>
<p class="lead">Para disfrutar del servicio por favor registrate o inicia sesión si ya tienes una cuenta.</p>
<p class="lead">
  <a href="/page/register" class="btn btn-lg btn-secondary">Registro</a>
  <a href="/page/login" class="btn btn-lg btn-primary">Login</a>
</p>
<% end %>

app/views/page/login.html.erb
<% @linkactive = 'login' %>
<%= form_tag(access_attempt_login_path, :method => 'post') do |f| %>
    <h2 class="form-signin-heading">Iniciar Sesión</h2>
    <label for="email" class="sr-only">Email</label>
    <input type="email" id="email" name="email" class="form-control" placeholder="Email" required autofocus>
    <label for="password" class="sr-only">Password</label>
    <input type="password" id="password" name="password" class="form-control" placeholder="Password" required>
    
    <button class="btn btn-lg btn-primary btn-block" type="submit">Login</button>
<% end %>

app/views/page/profile.html.erb
<% @linkactive = 'profile' %>
<ul class="nav nav-pills nav-justified" id="pills-tab" role="tablist">
  <li class="nav-item">
    <a class="nav-link " id="pills-banco-tab" data-toggle="pill" href="#pills-banco" role="tab" aria-controls="pills-banco" aria-selected="true">Banco</a>
  </li>
  <li class="nav-item">
    <a class="nav-link " id="pills-transfer-tab" data-toggle="pill" href="#pills-transfer" role="tab" aria-controls="pills-transfer" aria-selected="true">Transferir</a>
  </li>
  <li class="nav-item">
    <a class="nav-link active" id="pills-balance-tab" data-toggle="pill" href="#pills-balance" role="tab" aria-controls="pills-balance" aria-selected="false">Balance</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" id="pills-history-tab" data-toggle="pill" href="#pills-history" role="tab" aria-controls="pills-history" aria-selected="false">Historico</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" id="pills-comision-tab" data-toggle="pill" href="#pills-comision" role="tab" aria-controls="pills-comision" aria-selected="false">Comisiones</a>
  </li>
</ul>
<div class="tab-content" id="pills-tabContent">
    <div class="tab-pane fade  " id="pills-banco" role="tabpanel" aria-labelledby="pills-banco-tab">
      <ul class="nav nav-tabs justify-content-center" id="myTab" role="tablist">
        <li class="nav-item">
          <a class="nav-link active" id="fondear-tab" data-toggle="tab" href="#fondear" role="tab" aria-controls="fondear" aria-selected="true">Fondear Wallet</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" id="retirar-tab" data-toggle="tab" href="#retirar" role="tab" aria-controls="retirar" aria-selected="false">Retirar a Cuenta</a>
        </li>
      </ul>
      <div class="tab-content" id="myTabContent">
        <div class="tab-pane fade show active" id="fondear" role="tabpanel" aria-labelledby="fondear-tab">
          <%= form_tag(users_addmoney_path) do |f| %>
            <input type="hidden" name="addmoney[user_id]" id="user_id" value="<%= @user.id %>">
            <div class="form-row">
              <div class="col-6">
                <input type="text" class="form-control" placeholder="Nombre en la tarjeta" name="addmoney[name]" id="addmoney_name" required>
              </div>
              <div class="col-6">
                <input type="number" minlength="12" maxlength="16" class="form-control" placeholder="Numero de tarjeta" name="addmoney[card]" id="addmoney_card" required>
              </div>
              <div class="col-4">
                <input type="number" minlength="2" maxlength="2" class="form-control" placeholder="MM" name="addmoney[month]" id="addmoney_month" required>
              </div>
              <div class="col-4">
                <input type="number" minlength="2" maxlength="2" class="form-control" placeholder="YY" name="addmoney[year]" id="addmoney_year" required>
              </div>
              <div class="col-4">
                <input type="number" minlength="3" maxlength="4" class="form-control" placeholder="CVC" name="addmoney[cvc]" id="addmoney_cvc" required>
              </div>
              <div class="col-6">
                <input type="number" min="0" class="form-control" placeholder="Monto" name="addmoney[amount]" id="addmoney_amount" required>
              </div>
              <div class="col-6">
                <input class="btn btn-primary col-12" type="submit" name="commit" value="Procesar" data-disable-with="Procesar">
              </div>
            </div>
          <% end %>
          
        </div>
        <div class="tab-pane fade" id="retirar" role="tabpanel" aria-labelledby="profile-tab">
          <%= form_tag(users_retiremoney_path) do |f| %>
            <input type="hidden" name="retiremoney[user_id]" id="user_id" value="<%= @user.id %>">
            <div class="form-row">
              <div class="col-6">
                <select class="custom-select col-6" name="retiremoney[bank]" id="retiremoney_user_to_id" required>
                  <option value="" selected>Seleccione un banco</option>
                  <option value="Banamex">Banamex</option>
                  <option value="Banorte">Banorte</option>
                  <option value="Bancomer">Bancomer</option>
                  <option value="Bank of America">Bank of America</option>
                  <option value="HSBC">HSBC</option>
                </select>
              </div>
              <div class="col-6">
                <input type="number" minlength="12" maxlength="16" class="form-control" placeholder="Numero de tarjeta / cuenta" name="retiremoney[card]" id="retiremoney_card" required>
              </div>
              <div class="col-6">
                <input type="number" oninvalid="setCustomValidity('El monto no puede ser mayor a los $<%= @user.wallet_balance %> de tu balance')" onchange="try{setCustomValidity('')}catch(e){}" min="0" max="<%= @user.wallet_balance %>" class="form-control" placeholder="Monto" name="retiremoney[amount]" id="retiremoney_amount" required>
              </div>
              <div class="col-6">
                <input class="btn btn-primary col-12" type="submit" name="commit" value="Retirar" data-disable-with="Retirar">
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    <div class="tab-pane fade  " id="pills-transfer" role="tabpanel" aria-labelledby="pills-banco-tab">
      <form class="new_transfer" id="new_transfer" action="/transfers" accept-charset="UTF-8" method="post">
        <input type="hidden" name="transfer[user_id]" id="transfer_user_id" value="<%= @user.id %>">
        <div class="form-row">
          <div class="col-6">
            <%= render(:partial => 'layouts/userselect') %>
          </div>
          <div class="col-3">
            <input oninvalid="setCustomValidity('El monto no puede ser mayor a los $<%= @user.wallet_balance %> de tu balance')" onchange="try{setCustomValidity('')}catch(e){}" type="number" min="0" max="<%= @user.wallet_balance %>" step="0.1" class="form-control" placeholder="Monto" name="transfer[amount]" id="transfer_amount" required>
          </div>
          <div class="col-3">
            <input class="btn btn-primary col-12" type="submit" name="commit" value="Transferir" data-disable-with="Transferir">
          </div>
        </div>
      </form>
      
    </div>
    <div class="tab-pane fade show active jumbotron text-center" style="vertical-center" id="pills-balance" role="tabpanel" aria-labelledby="pills-profile-tab">
        <div class="jumbotron jumbotron-flat">
          <h1 class="display-3"><%= number_to_currency(@user.wallet_balance, precision: 2) %></h1>
        </div> 
    </div>
    <div class="tab-pane fade" id="pills-history" role="tabpanel" aria-labelledby="pills-history-tab">
      <table class="table table-hover">
        <thead>
          <tr>
            <th scope="col">#Transfer</th>
            <th scope="col">Fecha</th>
            <th scope="col">Monto</th>
            <th scope="col">Usuario</th>
        </tr>
        </thead>
        <tbody>
          <% @user.transfers.or(Transfer.where(user_to_id: @user.id)).order('created_at DESC').each do |transfer| %>
            <% if transfer.user_to_id? %>
            <% 
              if transfer.user_id ==  @user.id
                clase = "text-danger"
                usuario = User.find(transfer.user_to_id).name
              else 
                clase = "text-success"
                usuario = User.find(transfer.user_id).name
              end
            %>
            <tr>
              <th scope="row"><%= transfer.id %></th>
              <td><%= transfer.created_at.strftime("%d/%m/%Y - %I:%M%p") %></td>
              <td class="<%= clase %>"><%= number_to_currency(transfer.amount, precision: 2) %></td>
              <td class="<%= clase %>"><%= usuario %></td>
            </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
      
    </div>
    <div class="tab-pane fade" id="pills-comision" role="tabpanel" aria-labelledby="pills-contact-tab">
      <table class="table table-hover">
        <thead>
          <tr>
            <th scope="col">#Transfer</th>
            <th scope="col">Monto</th>
            <th scope="col">% Comisión</th>
            <th scope="col">Monto Comisión</th>
            <th scope="col">Tasa Fija</th>
            <th scope="col">Total</th>
        </tr>
        </thead>
        <tbody>
          <% @user.transfers.order('created_at DESC').each do |transfer| %>
            <% if transfer.commission %>
            <tr>
              <th scope="row"><%= transfer.id %></th>
              <td><strong><%= number_to_currency(transfer.amount, precision: 2) %></strong></td>
              <td><%= number_to_percentage(transfer.commission.commission_percent, precision: 1) %></td>
              <td><%= number_to_currency(transfer.commission.commission_amount, precision: 2) %></td>
              <td><%= number_to_currency(transfer.commission.fixed_rate, precision: 2) %></td>
              <td><strong><%= number_to_currency(transfer.commission.commission_amount + transfer.commission.fixed_rate, precision: 2) %></strong></td>
            </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
    </div>
</div>

app/views/page/register.html.erb
<% @linkactive = 'register' %>
<%= form_tag(users_path) do |f| %>
    <h2 class="form-signin-heading">Registro</h2>
    <label for="inputEmail" class="sr-only">Nombre</label>
    <input type="text" id="name" name="user[name]" class="form-control" placeholder="Nombre" required autofocus>
    <label for="inputEmail" class="sr-only">Email</label>
    <input type="email" id="email" name="user[email]" class="form-control" placeholder="Email" required autofocus>
    <label for="inputPassword" class="sr-only">Password</label>
    <input type="password" id="password" name="user[password]" class="form-control" placeholder="Password" required>
    
    <button class="btn btn-lg btn-primary btn-block" type="submit">Entrar</button>
<% end %>