config/routes.rb
Rails.application.routes.draw do
  
  root 'page#index'
  
  post 'access/attempt_login'
  get 'access/logout'
  
  resources :users do
    member do
      get :delete
    end
  end
  post 'users/addmoney'
  post 'users/retiremoney'
  
  resources :transfers do
    member do
      get :delete
    end
  end
  
  resources :commissions do
    member do
      get :delete
    end
  end
  
  get 'page/index'

  get 'page/profile'

  get 'page/register'

  get 'page/login'
  
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer class="mastfoot">
    <div class="inner">
      <p>Desarrollado por <a href="http://techingenius.com/equipo/jonasgraterol/" target="_blank">Jonas Graterol</a>, para <a href="https://www.conekta.com" target="_blank">Conekta</a>.</p>
    </div>
</footer>

app/views/layouts/_menunav.html.erb
<h4 class="masthead-brand">EWallet <small><% if @user.id? %> <%= @user.id.to_s.rjust(4, '0') %> - <%= @user.name %> <% end %></small></h4>
<nav class="nav nav-masthead">
<%= link_to("Home", {:controller => 'page', :action => 'index'}, :class=> @linkactive == 'index' ? 'nav-link active' : 'nav-link' )  %>
<%= 
  if @user.id? 
    link_to("Perfil", {:controller => 'page', :action => 'profile'}, :class=> @linkactive == 'profile' ? 'nav-link active' : 'nav-link' ) 
  end 
%>
<%= 
  if !@user.id? 
    link_to("Registro", {:controller => 'page', :action => 'register'}, :class=> @linkactive == 'register' ? 'nav-link active' : 'nav-link' ) 
  end  
%>
<%= 
  if !@user.id? 
    link_to("Login", {:controller => 'page', :action => 'login'}, :class=> @linkactive == 'login' ? 'nav-link active' : 'nav-link' ) 
  end 
%>
<%= 
  if @user.id? 
    link_to("Logout", access_logout_path, :class=>"nav-link" )  
  end   
%>
</nav>

app/views/layouts/_notifications.html.erb
<% if !flash[:success].blank? %>
    <div class="alert alert-success" role="alert">
      <%= flash[:success].html_safe %>
    </div>
<% end %>
<% if !flash[:notice].blank? %>
    <div class="alert alert-warning" role="alert">
      <%= flash[:notice].html_safe %>
    </div>
<% end %>
<% if !flash[:error].blank? %>
    <div class="alert alert-danger" role="alert">
      <%= flash[:error].html_safe %>
    </div>
<% end %>

app/views/layouts/_userselect.html.erb
<select class="custom-select col-7" name="transfer[user_to_id]" id="user_to_id" required>
    <option value="" selected>Seleccione destinatario...</option>
    <% User.all.each do |user| %>
        <% if session[:user_id] != user.id %>
           <option value="<%= user.id %>"><%= user.id.to_s.rjust(4, '0') %> - <%= user.name %></option>   
        <% end %>
    <% end %>
</select>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ConektaWallet</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
  </head>

  <body>
    <div class="site-wrapper">

      <div class="site-wrapper-inner">

        <div class="cover-container">
          
          <header class="masthead clearfix">
            <div class="inner">
              <%= render(:partial => 'layouts/menunav') %>
            </div>
          </header>
          
           <%= render(:partial => 'layouts/notifications') %>
          
          <main role="main" class="inner cover">
            <%= yield %>
          </main>
          
          <%= render(:partial => 'layouts/footer') %>
    
        </div>
    
      </div>
    </div>
  </body>
</html>